version: '3'

services:
  flask:
    build: ./flask
    container_name: flask_cont
    volumes:
      - ./flask/webapp/static/:/app/webapp/static/
    ports:
      - 5000:5000
    command: gunicorn --bind 0.0.0.0:5000 run:main()
    env_file:
      - ./env.dev
    restart: on-failure
