version: "3"

services:
  flask:
    build: ./flask
    container_name: flask_cont
    volumes:
      - ./flask/webapp/static/:/app/webapp/static/
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0
    env_file:
      - ./env.dev
    restart: on-failure
