version: '3'

services:
  flask:
    build: ./flask
    container_name: flask_cont
    volumes:
      - ./flask/webapp/static/:/app/webapp/static/
    expose:
      - 5000
    command: gunicorn --bind 0.0.0.0:5000 run:main()
    env_file:
      - ./env.dev
    restart: on-failure

  nginx:
    build: ./nginx
    container_name: flask_nginx
    ports:
      - 80:80
    depends_on:
      - flask
