version: '3'

services:
  flask:
    build: .
    container_name: flask_cont
    volumes:
      - ./webapp/static/:/app/webapp/static/
    ports:
      - "5000:5000"
    command: flask run
    restart: on-failure
