version: '3'

services:
  flask:
    build: ./flask
    container_name: flask_cont
    volumes:
      - ./flask/webapp/static/:/app/webapp/static/
      - ./data/certbot/conf:/app/flask/

    expose:
      - 5000
    command: gunicorn --bind 0.0.0.0:5000 run:main()
    env_file:
      - ./env.dev
    restart: on-failure

  nginx:
    build: ./nginx
    container_name: flask_nginx
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - flask
    restart: unless-stopped
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: unless-stopped
    entrypoint:  "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

